// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeProvider from "../app/providers/ThemeProvider"; // Import your ThemeProvider
import "./globals.css";
import SettingsButton from "./components/SettingsButton";
import Sidebar from "./components/Sidebar";
import Navbar from "./components/Navbar";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider> {/* Wrap the app with ThemeProvider */}
          <Box sx={{ display: "flex", flexDirection: "column", height: "100vh" }}>
            {/* Navbar at the top */}
            <Navbar />

            {/* Main content area */}
            <Box sx={{ display: "flex", flex: 1 }}>
              {/* Sidebar on the left */}
              <Sidebar />

              {/* Main content */}
              <Box sx={{ flex: 1, overflowY: "auto", p: 3 }}>
                {children}
              </Box>

              {/* SettingsButton and SettingsSidebar */}
              <SettingsButton />
            </Box>
          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
}