// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeProvider from "../app/providers/ThemeProvider"; // Import your ThemeProvider
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider> {/* Wrap the app with ThemeProvider */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}